Стилизация главной страницы под mobile
htmlacademy-adaptive/1496867-cat-energy-21 pull request #5
Opened 2020-12-27 22:26 UTC by AyBalatsan

2020-12-29 15:06 UTC, alexey-pd commented
есть ошибочки линтера https://github.com/htmlacademy-adaptive/1496867-cat-energy-21/pull/5/checks?check_run_id=1615039196

2020-12-29 15:06 UTC, alexey-pd commented on source/catalog.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>
лучше до стилей, чтобы лишнего не сбросить

2020-12-29 15:13 UTC, alexey-pd commented on source/form.html
> +            <label class="form__desc form__desc--color-add" for="sweetener-field">сахарозаменитель</label><br>
это точно модификатор -- ? больше похоже на элемент __

2020-12-29 15:14 UTC, alexey-pd commented on source/index.html
> +            <div class="block__text">
не очень понятно как связан block__text с diet элементами

2020-12-29 15:15 UTC, alexey-pd commented on source/index.html
> +              <div class="description__image--box">
так, модификатор не может быть без самого класса, который он модифицирует

2020-12-29 15:15 UTC, alexey-pd commented on source/index.html
> +                <p class="total__subtitle">снижение<br>веса</p>
лучше два спана - чем 1 бр

2020-12-29 15:15 UTC, alexey-pd commented on source/index.html
> +              <input class="visualization__scrolling" type="range" min="0" max="60" step="1" value="30">
name?

2020-12-29 15:16 UTC, alexey-pd commented on source/index.html
> +    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
нет, jquery нам не нужен на этом курсе и любом другом

2020-12-29 15:17 UTC, alexey-pd commented on source/js/js.js
> +$(document).ready(function(){
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload

2020-12-29 15:17 UTC, alexey-pd commented on source/js/js.js
> +$(document).ready(function(){
https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event а лучше

2020-12-29 15:17 UTC, alexey-pd commented on source/js/js.js
> +  $('.header__burger').click(function(event){
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

2020-12-29 15:18 UTC, alexey-pd commented on source/js/js.js
> +    $('.header__burger,.header__menu').toggleClass('active');
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList toggle

2020-12-29 15:18 UTC, alexey-pd commented on source/js/js.js
> +    $('.header__burger,.header__menu').toggleClass('active');
да и по бэм класс активный - не одиночный, а привязан к родителю (блоку)

2020-12-29 15:19 UTC, alexey-pd commented on source/less/button.less
> +.button, .product-button {
так дела не деляются, внутри product button можешь вызвать миксин button

2020-12-29 15:20 UTC, alexey-pd commented on source/less/button.less
> +  width: 280px;
ширины у кнопок нет глобальной и высоты, базовые размеры через padding, там где на всю ширину - на уровне элемента блока, дополнительным классом, а не для всех кнопок.

2020-12-29 15:20 UTC, alexey-pd commented on source/less/cat-profile.less
> +  .font__size(36px, 36px);
при равном line height удобнее писать 1

2020-12-29 15:21 UTC, alexey-pd commented on source/less/colors.less
> +@basic-white: #FFFFFF;
определись и используй один формат переменных - или _

2020-12-29 15:21 UTC, alexey-pd commented on source/less/description.less
> +  .center;
чтобы глаз не мылился удобно писать скобки у всех миксинов - даже не имеющих параметров

2020-12-29 15:22 UTC, alexey-pd commented on source/less/diet.less
> +  width: 320px;
сомнительно насчет фиксированных размеров - не думаю что решение оптимальное

2020-12-29 15:22 UTC, alexey-pd commented on source/less/diet.less
> +  font-weight: 400;
в переменную

2020-12-29 15:23 UTC, alexey-pd commented on source/less/diet.less
> +@media (max-width: 767px){
давай читать ТЗ и использовать подход mobile first, сначала стили мобильного - потом другие

в каждом селекторе по медиазапросу, а не в одном запросе куча селекторов

2020-12-29 15:23 UTC, alexey-pd commented on source/less/diet.less
> +@media (max-width: 767px){
дублирование не удобно поддерживать

2020-12-29 15:23 UTC, alexey-pd commented on source/less/diet.less
> +    margin-right: 11px;
точно все удобно?

2020-12-29 15:24 UTC, alexey-pd commented on source/less/example.less
> +  .font__arial;
вызывай миксины всегда вверху - на случай если вдруг надо быстро прочитать код и один какой-то параметр переопределить

2020-12-29 15:24 UTC, alexey-pd commented on source/less/example.less
> +    .size (280px, 320px);
100%?

2020-12-29 15:25 UTC, alexey-pd commented on source/less/mixins.less
> +  @media(max-width: 768px){
окей - только на айфонах тоже отступы требуются и без max-width, только min

2020-12-29 15:27 UTC, alexey-pd commented on source/less/mixins.less
> +.font__size (@font-size, @line-height){
можно указывать в аргументах параметры по умолчанию, есть в доке примеры

2020-12-29 15:27 UTC, alexey-pd commented on source/less/navigation.less
> +  width: 320px;
------- не надо ширину

2020-12-29 15:28 UTC, alexey-pd commented on source/less/navigation.less
> +  .page-header:before{
&:before

2020-12-29 15:29 UTC, alexey-pd commented on source/less/navigation.less
> +.main-nav {
так какой это блок?

в каждом файле стили только конкретного блока - совпадающего по имени класса и названию файла

2020-12-29 15:29 UTC, alexey-pd commented on source/less/navigation.less
> +  .page-header__logo {
а тут просто - всё

2020-12-29 15:29 UTC, alexey-pd commented on source/less/navigation.less
> +    width: 320px;
-

2020-12-29 15:30 UTC, alexey-pd commented on source/less/style.less
> +@import "mixins";
цветы шрифты и прочие не блоки - смело кидай в base

2020-12-29 15:30 UTC, alexey-pd commented on source/less/style.less
> +@import "navigation";
а это вот все в папку blocks

2020-12-29 15:30 UTC, alexey-pd commented on source/less/style.less
> +  height: 1px;
по критериям только импорты можно

2020-12-29 17:38 UTC, AyBalatsan commented on source/less/navigation.less
> +    width: 320px;
Поясни, что значит просто точка

2020-12-29 17:39 UTC, AyBalatsan commented on source/less/navigation.less
> +  .page-header__logo {
всмысле?

2020-12-29 17:39 UTC, AyBalatsan commented on source/less/navigation.less
> +  width: 320px;
Просто убрать?

2020-12-29 17:40 UTC, AyBalatsan commented on source/less/example.less
> +    .size (280px, 320px);
Это к чему? я не понимаю такие короткие вопросы

2020-12-29 17:41 UTC, AyBalatsan commented on source/less/diet.less
> +    margin-right: 11px;
А что не так?

2020-12-29 17:42 UTC, AyBalatsan commented on source/less/diet.less
> +@media (max-width: 767px){
То есть переделывать медиа запросы по каждому классу, расписывать отдельно?

2020-12-30 06:17 UTC, alexey-pd commented on source/index.html
> +              <div class="description__image--box">
https://up.htmlacademy.ru/adaptive/21/criteries#b5 критерий Б5

2020-12-30 06:18 UTC, alexey-pd commented on source/js/js.js
> +  $('.header__burger').click(function(event){
файл обычно называют script или main.js

2020-12-30 06:36 UTC, alexey-pd commented on source/less/diet.less
> +@media (max-width: 767px){
max на min width - переделывать точно

остальное смотри сам, но пока стилей не много... вообщем это именно вопрос удобства

2020-12-30 06:43 UTC, alexey-pd commented on source/less/diet.less
> +    margin-right: 11px;
каждый браузер округляет размеры по своему, если писать кратно 2 будет более стабильно, например 10px

возможно это попытка идти по макету, но увы любой макет содержит расхождения и задача разработчика - не повторить все ошибки дизайнера, а сделать более прогнозируемо и удобно для себя

2020-12-30 06:47 UTC, alexey-pd commented on source/less/example.less
> +    .size (280px, 320px);
не надо подстраивать ширину блоков под каждое устройство

айфоны бывают 320 375 минимум пикселей, надо тянуть по ширине экрана, но так как элемент уже блочный можно писать 100% или не писать ничего.

2020-12-30 06:47 UTC, alexey-pd commented on source/less/navigation.less
> +  width: 320px;
просто не писать - да

2020-12-30 06:48 UTC, alexey-pd commented on source/less/navigation.less
> +  .page-header__logo {
https://up.htmlacademy.ru/adaptive/21/criteries#b13 почитай все критерии внимательно пожалуйста

2020-12-30 06:49 UTC, alexey-pd commented on source/less/navigation.less
> +  .page-header__logo {
**особенно этот** Используя CSS-препроцессор, нужно разделить код таким образом, чтобы каждый блок был в своём файле. Для каждого БЭМ-блока нужно создать отдельный файл стилей.

2020-12-30 06:49 UTC, alexey-pd commented on source/less/navigation.less
> +    width: 320px;
убирай ширину как выше писалось - фиксированную

2020-12-30 06:50 UTC, alexey-pd commented
тесты красные всё еще, запускай локально перед коммитом пожалуйста

2020-12-30 21:29 UTC, AyBalatsan commented on source/index.html
> +            <div class="block__text">
Я этим блоком выравнивал текст в данном блоке

2020-12-30 21:38 UTC, AyBalatsan commented on source/index.html
> +              <div class="description__image--box">
Не совсем понял как назвать. description__image--mod1?

2021-01-08 12:12 UTC, andreysgra requested changes
Во всех файлах разметки есть ошибки валидации (проверить можно [здесь](https://validator.w3.org/nu/#textarea)) и ошибки именования классов по БЭМ (проверить можно [здесь](https://yoksel.github.io/html-tree/)).

Всё это нужно устранить.

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/example.less
> +}
Что эти селекторы делают в файле **example.less**?

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/footer.less
> +.footer-inform__wrapper{
`footer-inform__wrapper` - это элемент блока `footer-inform`. У нас же файл **footer.less**. Тогда класс должен называться `footer__inform-wrapper`.

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/footer.less
> +}
Селекторы классов не в том файле, где положено.

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/footer.less
> +}
Селекторы классов не в том файле, где положено.

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/navigation.less
> +}
В этом файле вообще всё, что угодно, кроме классов блока `navigation`.

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/product.less
> +.main-catalog__title {
В **main-catalog.less**

2021-01-08 12:12 UTC, andreysgra commented on source/less/blocks/product.less
> +.additional-goods__list{
В **additional-goods.less**

2021-01-08 12:12 UTC, andreysgra commented on source/less/font.less
> +@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500&display=swap');
Шрифты должны быть подключены локально (через @font-face) - критерий [Б9](https://up.htmlacademy.ru/adaptive/21/criteries#b9).

2021-01-08 12:12 UTC, andreysgra commented on source/less/style.less
> +}
В файле style.less может быть только импорт - то есть подключение внешних файлов препроцессора. Селекторов быть не должно.

2021-01-09 22:11 UTC, AyBalatsan commented on source/less/font.less
> +@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500&display=swap');
Исправил

2021-01-10 01:11 UTC, AyBalatsan commented on source/less/blocks/diet.less
> +}
Исправил на diet__icon--indents-slim и diet__icon--indents-strong

2021-01-10 01:15 UTC, AyBalatsan commented on source/less/blocks/navigation.less
> +}
Нужно переименовать в header?

2021-01-10 15:40 UTC, andreysgra requested changes

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/additional-goods.less
> +.additional-goods-title__wrapper{
```suggestion
.additional-goods__title-wrapper{
```

Так как это элемент БЭМ блока `additional-goods`. А ваше наименование класса говорит о том, что это элемент блока `additional-goods-title`.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/additional-goods.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/additional-goods.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/additional-goods.less
> +}
В файл **bonus.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **main-form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
```suggestion
.cat-profile__wrapper{
  .center;
}
.cat-profile__item{
  display: flex;
  justify-content: flex-start;
  align-items: baseline;
}
```
Думаю, что так.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +.cat-data__list{
```suggestion
.cat-profile__list{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **program-selection.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +.radio__icon{
```suggestion
.form__radio-icon{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +.form__radio:checked + .radio__icon::before {
```suggestion
.form__radio:checked + .form__radio-icon::before {
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ (основываясь на том, что это элементы блока `form`).

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
В файл **form.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +  }
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ (класс `checkbox__icon`).

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/cat-profile.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/diet.less
> +}
Нужно переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/diet.less
> +.diet-weight-gain{
```suggestion
.diet__weight-gain{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
В файл **total.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
Надо подумать над тем - действительно ли это элемент блока `subtitle`? А вообще, есть ли такой БЭМ блок `subtitle`?

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +.maney-total{
```suggestion
.money-total{
```
Заодно возникает вопрос - а это БЭМ блок?

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
Если это БЭМ блок `visualization` и его элемент `visualization__img`, то значит нужно их перенести в файл **visualization.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
А вообще, есть ли такой БЭМ блок `scroll`?

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
В файл **slider.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/example.less
> +}
А вообще, есть ли такой БЭМ блок `scroll`?

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +.footer-inform__wrapper{
```suggestion
.footer__inform-wrapper{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +}
В файл **inform.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +.page-footer__copyright{
```suggestion
footer__copyright{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +}
В файл **social.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +.page-footer__social{
```suggestion
.footer__social{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/footer.less
> +.page-footer__copyright{
```suggestion
.footer__copyright{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/header.less
> +}
```suggestion
.header__mobile {
  .center;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 66px;
}
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/header.less
> +}
В файл main-nav.less

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/header.less
> +}
В файл **site-list.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
В файл **main-catalog.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
В файл **product.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
В файл **details.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
В файл **product.less**

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
Переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/blocks/product.less
> +}
Переименовать классы согласно БЭМ.

2021-01-10 15:40 UTC, andreysgra commented on source/less/button.less
> +.button-all{
```suggestion
.button--all{
```

2021-01-10 15:40 UTC, andreysgra commented on source/less/button.less
> +.button-form{
```suggestion
.button--form{
```

2021-01-10 15:42 UTC, andreysgra requested changes

2021-01-10 15:42 UTC, andreysgra commented on source/less/blocks/diet.less
> +.block__text{
Может `diet__text`? Префикс `block` указывает на то, что это элемент блока block.

2021-01-10 16:40 UTC, AyBalatsan commented on source/less/blocks/product.less
> +}
Дак он и так там, или я что то не понимаю?

2021-01-10 23:32 UTC, AyBalatsan commented on source/less/blocks/additional-goods.less
> +.additional-goods-title__wrapper{
Выполнил

2021-01-10 23:32 UTC, AyBalatsan commented on source/less/blocks/additional-goods.less
> +}
выполнил

2021-01-10 23:45 UTC, AyBalatsan commented on source/less/blocks/additional-goods.less
> +}
Выполнил

2021-01-11 00:14 UTC, AyBalatsan commented on source/less/blocks/product.less
> +}
Выполнил

2021-01-11 00:16 UTC, AyBalatsan commented on source/less/blocks/product.less
> +}
выполнил

2021-01-11 00:16 UTC, AyBalatsan commented on source/less/button.less
> +.button-all{
Выполнил

2021-01-11 00:16 UTC, AyBalatsan commented on source/less/button.less
> +.button-form{
выполнил

2021-01-11 00:17 UTC, AyBalatsan commented on source/less/blocks/diet.less
> +.block__text{
выплнил

2021-01-12 17:23 UTC, andreysgra requested changes

2021-01-12 17:23 UTC, andreysgra commented on source/less/blocks/all-goods.less
> +.plus{
```suggestion
.all-goods__plus{
```
Класс `plus` указывает на то, что это БЭМ блок, но это не самостоятельная сущность, а значит нужен класс элемента.

2021-01-12 17:23 UTC, andreysgra commented on source/less/blocks/product.less
> +}
В файл **details.less**

2021-01-12 17:23 UTC, andreysgra commented on source/less/blocks/site-navigation.less
> +}
```suggestion
.site-navigation__link:hover{
  opacity: 0.6;
}
.site-navigation__link:active{
  opacity: 0.3;
}
```

Лишние подчёркивания.

2021-01-12 17:23 UTC, andreysgra commented on source/less/mixins.less
> +}
`.diet__link` - а это точно миксин? Что-то мне подсказывает, что это класс БЭМ элемента. Если так, то нужно перенести в файл **diet.less**.

2021-01-12 17:23 UTC, andreysgra commented on source/less/page-main.less
> +}
`page-main` - класс БЭМ блока, а файлы блоков должны находиться в каталоге **blocks**.

2021-01-12 17:25 UTC, andreysgra commented
На этот раз почти идеально, но всё же есть несколько ошибок.

2021-01-12 17:27 UTC, merged